# Generated by Django 5.1.7 on 2025-04-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0013_alter_user_groups_alter_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(default='11111111111111', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='01111111111', max_length=15, unique=True),
        ),
    ]
